"use client";
import { useMemo, useState } from "react";
import { runTests } from "@/engine/run-tests";
import { generateIncident, mintCredential, proposeFix } from "@/lib";
import { mockMessages } from "@/lib/mocks/agents";
import type { FixCandidate, TestResult } from "@/lib/types";
const incident = generateIncident();
export function IncidentWorkbench() {
  const [source, setSource] = useState(incident.files[0].content); const [selectedFixes, setSelectedFixes] = useState<string[]>([]); const [result, setResult] = useState<TestResult>(); const [credentialOpen, setCredentialOpen] = useState(false);
  const fixes = useMemo(() => proposeFix({ files: [{ path: incident.activeFile, content: source }], messages: mockMessages }), [source]);
  const applyFix = (fix: FixCandidate) => { setSelectedFixes((current) => [...current, fix.id]); if (fix.faultTag === "verified") setSource(fix.patch); };
  const verify = () => { const next = runTests([{ path: incident.activeFile, content: source }]); setResult(next); if (next.passed) setCredentialOpen(true); };
  const credential = mintCredential({ incidentId: incident.id, startedAt: "", selectedFixIds: selectedFixes, caughtIncorrectAiFix: selectedFixes.some((id) => id !== "atomic-payment"), testResult: result });
  return <main className="shell"><header className="topbar"><div><span className="brand">PAGER</span><span className="environment">production / {incident.service}</span></div><span className="timer">02:14 elapsed</span></header><section className={result?.passed ? "alert cleared" : "alert"}><strong>{result?.passed ? "RESOLVED" : `${incident.severity} · PAYMENT INCIDENT`}</strong><span>{result?.passed ? "Duplicate charge rate has returned to baseline." : incident.alert}</span></section><section className="mission"><span>INCIDENT / {incident.title}</span><h1>Find the cause. Don’t ship the confident wrong fix.</h1></section><div className="workbench"><section className="panel code-panel" aria-label="Checkout service code"><div className="panel-heading"><span>{incident.activeFile}</span><span>TypeScript</span></div><textarea aria-label="Checkout service editor" value={source} onChange={(event) => setSource(event.target.value)} spellCheck={false} /><div className="verify-row"><button className="verify" onClick={verify}>Run verification suite</button>{result && <span className={result.passed ? "result pass" : "result fail"}>{result.summary}</span>}</div></section><aside className="side-stack"><section className="panel messages" aria-label="Incident chat"><div className="panel-heading">INCIDENT CHANNEL <span>3 online</span></div>{mockMessages.map((message) => <article key={message.id} className="message"><strong>{message.author}</strong><time>{message.timestamp}</time><p>{message.body}</p></article>)}</section><section className="panel fixes" aria-label="AI pair recommendations"><div className="panel-heading">AI PAIR · RECOMMENDATIONS</div>{fixes.map((fix) => <article key={fix.id} className="fix"><div><strong>{fix.title}</strong><p>{fix.rationale}</p></div><button onClick={() => applyFix(fix)} disabled={selectedFixes.includes(fix.id)}>{selectedFixes.includes(fix.id) ? "Reviewed" : fix.faultTag === "verified" ? "Apply" : "Reject"}</button></article>)}</section></aside></div>{result && <section className="test-panel"><strong>VERIFICATION OUTPUT</strong>{result.tests.map((test) => <div key={test.name}><span className={test.passed ? "pass" : "fail"}>{test.passed ? "PASS" : "FAIL"}</span><span>{test.name}</span><em>{test.detail}</em></div>)}</section>}{credentialOpen && <section className="credential" role="status"><button aria-label="Close credential" onClick={() => setCredentialOpen(false)}>×</button><span>EXECUTION-VERIFIED</span><h2>{credential.title}</h2><p>{credential.summary}</p><small>Issued {credential.issuedAt} · Mission: {incident.title}</small></section>}</main>;
}
